using Microsoft.JSInterop;

namespace TinacoPro.Web.Services;

public class LocalizationService
{
    private readonly IJSRuntime _jsRuntime;
    private string _currentLanguage = "en";
    private Dictionary<string, Dictionary<string, string>> _translations = new();

    public LocalizationService(IJSRuntime jsRuntime)
    {
        _jsRuntime = jsRuntime;
        InitializeTranslations();
    }

    public string CurrentLanguage => _currentLanguage;

    public event Action? OnLanguageChanged;

    private void InitializeTranslations()
    {
        _translations = new Dictionary<string, Dictionary<string, string>>
        {
            ["en"] = new Dictionary<string, string>
            {
                ["Dashboard"] = "Dashboard",
                ["Products"] = "Products",
                ["RawMaterials"] = "Raw Materials",
                ["ProductionOrders"] = "Production Orders",
                ["Suppliers"] = "Suppliers",
                ["Reports"] = "Reports",
                ["ProductCatalog"] = "Product Catalog",
                ["RawMaterialsInventory"] = "Raw Materials Inventory",
                ["NewProduct"] = "New Product",
                ["NewMaterial"] = "New Material",
                ["NewProductionOrder"] = "New Production Order",
                ["NewSupplier"] = "New Supplier",
                ["Name"] = "Name",
                ["Model"] = "Model",
                ["Size"] = "Size",
                ["Capacity"] = "Capacity (L)",
                ["Status"] = "Status",
                ["Actions"] = "Actions",
                ["Edit"] = "Edit",
                ["Delete"] = "Delete",
                ["Active"] = "Active",
                ["Inactive"] = "Inactive",
                ["Code"] = "Code",
                ["Unit"] = "Unit",
                ["CurrentStock"] = "Current Stock",
                ["MinimumStock"] = "Minimum Stock",
                ["UnitCost"] = "Unit Cost",
                ["OrderNumber"] = "Order Number",
                ["Product"] = "Product",
                ["Quantity"] = "Quantity",
                ["OrderDate"] = "Order Date",
                ["CompletedDate"] = "Completed Date",
                ["Pending"] = "Pending",
                ["InProgress"] = "In Progress",
                ["Completed"] = "Completed",
                ["Contact"] = "Contact",
                ["Phone"] = "Phone",
                ["Email"] = "Email",
                ["Address"] = "Address",
                ["ProductionSummary"] = "Production Summary",
                ["InventoryStatus"] = "Inventory Status",
                ["ProductCatalogSummary"] = "Product Catalog Summary",
                ["Today"] = "Today",
                ["ThisWeek"] = "This Week",
                ["ThisMonth"] = "This Month",
                ["OrdersCompleted"] = "Orders Completed",
                ["TotalUnits"] = "Total Units",
                ["LowStockAlert"] = "Low Stock Alert!",
                ["MaterialsRunningLow"] = "materials are running low",
                ["AllMaterialsStocked"] = "All materials are adequately stocked.",
                ["TotalProducts"] = "Total Products",
                ["ActiveProducts"] = "Active Products",
                ["InactiveProducts"] = "Inactive Products",
                ["LowStockItems"] = "Low Stock Items",
                ["Loading"] = "Loading...",
                ["DailyProduction"] = "Daily Production",
                ["StockIn"] = "Stock In",
                ["StockOut"] = "Stock Out",
                ["ProductionDate"] = "Production Date",
                ["SaveDailyProduction"] = "Save Daily Production",
                ["HistoricalProduction"] = "Historical Production",
                ["TotalRawMaterials"] = "Total Raw Materials",
                ["ProductionOverview"] = "Production Overview",
                ["PendingOrders"] = "Pending Orders",
                ["CompletedToday"] = "Completed Today",
                ["CompletedThisWeek"] = "Completed This Week",
                ["CompletedThisMonth"] = "Completed This Month",
                ["Orders"] = "Orders",
                ["AdequateStock"] = "Adequate Stock",
                // Finished Goods
                ["FinishedGoods"] = "Finished Goods",
                ["FinishedGoodsInventory"] = "Finished Goods Inventory",
                ["NewFinishedGoodEntry"] = "New Finished Good Entry",
                ["BatchNumber"] = "Batch Number",
                ["QuantityProduced"] = "Quantity Produced",
                ["AdjustStock"] = "Adjust Stock",
                // Shipments
                ["Shipments"] = "Shipments",
                ["ShipmentManagement"] = "Shipment Management",
                ["NewShipment"] = "New Shipment",
                ["EditShipment"] = "Edit Shipment",
                ["ShipmentNumber"] = "Shipment #",
                ["ShipmentDate"] = "Shipment Date",
                ["Customer"] = "Customer",
                ["CustomerName"] = "Customer Name",
                ["CustomerContact"] = "Customer Contact",
                ["Destination"] = "Destination",
                ["DestinationAddress"] = "Destination Address",
                ["City"] = "City",
                ["ZoneState"] = "Zone/State",
                ["FilterByStatus"] = "Filter by Status",
                ["AllStatuses"] = "All Statuses",
                ["MarkAsInTransit"] = "Mark as In Transit",
                ["MarkAsDelivered"] = "Mark as Delivered",
                ["CancelShipment"] = "Cancel Shipment",
                ["Delivered"] = "Delivered",
                ["Cancelled"] = "Cancelled",
                ["InTransit"] = "In Transit",
                // Template Builder
                ["TemplateBuilder"] = "Template Builder",
                ["TemplateManagement"] = "Template Management",
                ["NewTemplate"] = "New Template",
                ["EditTemplate"] = "Edit Template",
                ["Parts"] = "Parts",
                ["AddPart"] = "Add Part",
                ["CostSummary"] = "Cost Summary",
                ["MaterialCost"] = "Material Cost",
                ["LaborCost"] = "Labor Cost",
                ["EstTime"] = "Est. Time",
                ["TotalCost"] = "Total Cost",
                ["Template"] = "Template",
                ["NoTemplate"] = "No template",
                ["ProductionTemplate"] = "Production Template",
                ["ProductionTemplateOptional"] = "Production Template (Optional)",
                ["SelectTemplateHelp"] = "Select a template to define BOM and costs",
                // Shifts
                ["Shift"] = "Shift",
                ["Morning"] = "Morning",
                ["Afternoon"] = "Afternoon",
                ["Night"] = "Night",
                // Common
                ["Notes"] = "Notes",
                ["ProductionNotes"] = "Production Notes",
                ["Cancel"] = "Cancel",
                ["Save"] = "Save",
                ["Description"] = "Description",
                ["Optional"] = "Optional",
                ["Required"] = "Required",
                ["FinishedGood"] = "Finished Good",
                ["FinishedGoodOptional"] = "Finished Good (Optional)",
                ["ConfirmDelete"] = "Confirm Delete",
                ["AreYouSure"] = "Are you sure you want to delete this?",
                ["TemplateName"] = "Template Name",
                ["ModelType"] = "Model Type",
                ["EditPart"] = "Edit Part",
                ["ParentPart"] = "Parent Part",
                ["PartType"] = "Part Type",
                ["PartName"] = "Part Name",
                ["UnitCost"] = "Unit Cost ($)",
                ["EstimatedMinutes"] = "Estimated Minutes",
                ["MaterialName"] = "Material Name",
                ["MaterialCode"] = "Material Code",
                ["MinimumStock"] = "Minimum Stock",
                ["AddChildPart"] = "Add Child Part",
                ["ProductionOrder"] = "Production Order",
                ["ExpectedDeliveryDate"] = "Expected Delivery Date",
                ["NewFinishedGoodEntry"] = "New Finished Good Entry",
                ["RawMaterial"] = "Raw Material",
                ["None"] = "None",
                ["RootLevel"] = "Root Level",
                ["Quantity"] = "Quantity",
                ["ProductionDate"] = "Production Date",
                ["DailyProductionEntry"] = "Daily Production Entry",
                ["EnterProductionForDate"] = "Enter Production for Date",
                ["EnterQuantitiesForEachProduct"] = "Enter quantities for each product",
                ["Units"] = "units",
                ["SaveDailyProduction"] = "Save Daily Production",
                ["NoActiveProductsFound"] = "No active products found. Please add products first.",
                ["HistoricalDailyProduction"] = "Historical Daily Production",
                ["NoProductionHistoryFound"] = "No production history found. Start by entering your first daily production!",
                ["ProductionOrdersManagement"] = "Production Orders Management",
                ["MarkAsInProgress"] = "Mark as In Progress",
                ["MarkAsCompleted"] = "Mark as Completed",
                ["EditProductionOrder"] = "Edit Production Order",
                // MainLayout
                ["SwitchToLightMode"] = "Switch to Light Mode",
                ["SwitchToDarkMode"] = "Switch to Dark Mode",
                ["Language"] = "Language",
                // Products page
                ["EditProduct"] = "Edit Product",
                ["NoProductsFound"] = "No products found. Create your first product!",
                ["CapacityLiters"] = "Capacity (Liters)",
                ["NoTemplateSelected"] = "No Template",
                ["TemplateCosts"] = "Template Costs",
                ["Total"] = "Total",
                ["ProductCreated"] = "Product created successfully!",
                ["ProductUpdated"] = "Product updated successfully!",
                // Raw Materials page
                ["Category"] = "Category",
                ["MinStock"] = "Min Stock",
                ["NewMaterial"] = "New Material",
                ["EditMaterial"] = "Edit Material",
                ["UnitFormat"] = "Unit (kg, L, pcs)",
                ["LowStockAlertCount"] = "material(s) are running low on stock!",
                ["NoMaterialsFound"] = "No materials found. Create your first material!",
                ["Reason"] = "Reason",
                ["AddStock"] = "Add Stock",
                ["RemoveStock"] = "Remove Stock",
                // Production Orders page
                ["CreateOrder"] = "Create Order",
                ["Start"] = "Start",
                ["Complete"] = "Complete",
                ["NoOrdersFound"] = "No production orders found. Create your first order!",
                ["OrderAutoStarted"] = "Order automatically set to In Progress",
                ["OrderAutoCompleted"] = "Order automatically completed - target quantity reached",
                // Suppliers page
                ["EditSupplier"] = "Edit Supplier",
                ["CompanyName"] = "Company Name",
                ["ContactName"] = "Contact Name",
                ["NoSuppliersFound"] = "No suppliers found. Create your first supplier!",
                // Finished Goods page
                ["Order"] = "Order",
                ["NoFinishedGoodsFound"] = "No finished goods found. Complete a production order to create finished goods!",
                // Shippings page
                ["CancelShipmentAction"] = "Cancel Shipment",
                ["ShipmentUpdated"] = "Shipment updated successfully",
                ["ShipmentCreated"] = "Shipment created successfully",
                ["ShipmentCancelled"] = "Shipment cancelled successfully",
                ["ShipmentStatusUpdated"] = "Shipment status updated",
                // Reports page
                ["ReportsAnalytics"] = "Reports & Analytics",
                ["ReportDesigner"] = "Report Designer",
                ["ReportType"] = "Report Type",
                ["ProductionSummaryReport"] = "Production Summary",
                ["InventoryStatusReport"] = "Inventory Status",
                ["RawMaterialsUsage"] = "Raw Materials Usage",
                ["OrdersAnalysis"] = "Orders Analysis",
                ["CustomReport"] = "Custom Report",
                ["StartDate"] = "Start Date",
                ["EndDate"] = "End Date",
                ["Generate"] = "Generate",
                ["ReportOptions"] = "Report Options",
                ["IncludeCharts"] = "Include Charts",
                ["IncludeDetails"] = "Include Details",
                ["GroupByProduct"] = "Group by Product",
                ["ExportPDF"] = "Export PDF",
                ["ExportExcel"] = "Export Excel",
                ["SaveTemplate"] = "Save Template",
                ["ProductionSummaryReportTitle"] = "Production Summary Report",
                ["InventoryStatusReportTitle"] = "Inventory Status Report",
                ["ProductTypes"] = "Product Types",
                ["AvgUnitsOrder"] = "Avg Units/Order",
                ["ProductionDetails"] = "Production Details",
                ["TotalMaterials"] = "Total Materials",
                ["LowStockAlerts"] = "Low Stock Alerts",
                ["AttentionRequired"] = "Attention Required:",
                ["MaterialsNeedRestocking"] = "materials need restocking",
                ["Material"] = "Material",
                ["Shortage"] = "Shortage",
                ["CustomReportBuilder"] = "Custom Report Builder",
                ["CustomReportDescription"] = "Design your own reports by selecting specific metrics, groupings, and visualizations. This feature allows you to create tailored reports for your specific business needs.",
                ["CurrentStatusAsOf"] = "Current Status as of",
                // Daily Production automation messages
                ["ProductionOrdersCreatedSuccess"] = "Production orders created successfully for {0} product(s)!",
                ["EnterQuantityWarning"] = "Please enter quantities for at least one product.",
                ["ErrorCreatingOrders"] = "Error creating production orders: {0}",
            },
            ["es"] = new Dictionary<string, string>
            {
                ["Dashboard"] = "Panel de Control",
                ["Products"] = "Productos",
                ["RawMaterials"] = "Materias Primas",
                ["ProductionOrders"] = "Órdenes de Producción",
                ["Suppliers"] = "Proveedores",
                ["Reports"] = "Reportes",
                ["ProductCatalog"] = "Catálogo de Productos",
                ["RawMaterialsInventory"] = "Inventario de Materias Primas",
                ["NewProduct"] = "Nuevo Producto",
                ["NewMaterial"] = "Nueva Materia Prima",
                ["NewProductionOrder"] = "Nueva Orden de Producción",
                ["NewSupplier"] = "Nuevo Proveedor",
                ["Name"] = "Nombre",
                ["Model"] = "Modelo",
                ["Size"] = "Tamaño",
                ["Capacity"] = "Capacidad (L)",
                ["Status"] = "Estado",
                ["Actions"] = "Acciones",
                ["Edit"] = "Editar",
                ["Delete"] = "Eliminar",
                ["Active"] = "Activo",
                ["Inactive"] = "Inactivo",
                ["Code"] = "Código",
                ["Unit"] = "Unidad",
                ["CurrentStock"] = "Stock Actual",
                ["MinimumStock"] = "Stock Mínimo",
                ["UnitCost"] = "Costo Unitario",
                ["OrderNumber"] = "Número de Orden",
                ["Product"] = "Producto",
                ["Quantity"] = "Cantidad",
                ["OrderDate"] = "Fecha de Orden",
                ["CompletedDate"] = "Fecha de Completado",
                ["Pending"] = "Pendiente",
                ["InProgress"] = "En Progreso",
                ["Completed"] = "Completado",
                ["Contact"] = "Contacto",
                ["Phone"] = "Teléfono",
                ["Email"] = "Correo",
                ["Address"] = "Dirección",
                ["ProductionSummary"] = "Resumen de Producción",
                ["InventoryStatus"] = "Estado de Inventario",
                ["ProductCatalogSummary"] = "Resumen de Catálogo",
                ["Today"] = "Hoy",
                ["ThisWeek"] = "Esta Semana",
                ["ThisMonth"] = "Este Mes",
                ["OrdersCompleted"] = "Órdenes Completadas",
                ["TotalUnits"] = "Unidades Totales",
                ["LowStockAlert"] = "¡Alerta de Stock Bajo!",
                ["MaterialsRunningLow"] = "materiales tienen stock bajo",
                ["AllMaterialsStocked"] = "Todas las materias primas tienen stock adecuado.",
                ["TotalProducts"] = "Total de Productos",
                ["ActiveProducts"] = "Productos Activos",
                ["InactiveProducts"] = "Productos Inactivos",
                ["LowStockItems"] = "Artículos con Stock Bajo",
                ["Loading"] = "Cargando...",
                ["DailyProduction"] = "Producción Diaria",
                ["StockIn"] = "Entrada de Stock",
                ["StockOut"] = "Salida de Stock",
                ["ProductionDate"] = "Fecha de Producción",
                ["SaveDailyProduction"] = "Guardar Producción Diaria",
                ["HistoricalProduction"] = "Producción Histórica",
                ["TotalRawMaterials"] = "Total de Materias Primas",
                ["ProductionOverview"] = "Resumen de Producción",
                ["PendingOrders"] = "Órdenes Pendientes",
                ["CompletedToday"] = "Completado Hoy",
                ["CompletedThisWeek"] = "Completado Esta Semana",
                ["CompletedThisMonth"] = "Completado Este Mes",
                ["Orders"] = "Órdenes",
                ["AdequateStock"] = "Stock Adecuado",
                // Finished Goods
                ["FinishedGoods"] = "Productos Terminados",
                ["FinishedGoodsInventory"] = "Inventario de Productos Terminados",
                ["NewFinishedGoodEntry"] = "Nueva Entrada de Producto Terminado",
                ["BatchNumber"] = "Número de Lote",
                ["QuantityProduced"] = "Cantidad Producida",
                ["AdjustStock"] = "Ajustar Stock",
                // Shipments
                ["Shipments"] = "Envíos",
                ["ShipmentManagement"] = "Gestión de Envíos",
                ["NewShipment"] = "Nuevo Envío",
                ["EditShipment"] = "Editar Envío",
                ["ShipmentNumber"] = "# de Envío",
                ["ShipmentDate"] = "Fecha de Envío",
                ["Customer"] = "Cliente",
                ["CustomerName"] = "Nombre del Cliente",
                ["CustomerContact"] = "Contacto del Cliente",
                ["Destination"] = "Destino",
                ["DestinationAddress"] = "Dirección de Destino",
                ["City"] = "Ciudad",
                ["ZoneState"] = "Zona/Estado",
                ["FilterByStatus"] = "Filtrar por Estado",
                ["AllStatuses"] = "Todos los Estados",
                ["MarkAsInTransit"] = "Marcar como En Tránsito",
                ["MarkAsDelivered"] = "Marcar como Entregado",
                ["CancelShipment"] = "Cancelar Envío",
                ["Delivered"] = "Entregado",
                ["Cancelled"] = "Cancelado",
                ["InTransit"] = "En Tránsito",
                // Template Builder
                ["TemplateBuilder"] = "Constructor de Plantillas",
                ["TemplateManagement"] = "Gestión de Plantillas",
                ["NewTemplate"] = "Nueva Plantilla",
                ["EditTemplate"] = "Editar Plantilla",
                ["Parts"] = "Partes",
                ["AddPart"] = "Agregar Parte",
                ["CostSummary"] = "Resumen de Costos",
                ["MaterialCost"] = "Costo de Material",
                ["LaborCost"] = "Costo de Mano de Obra",
                ["EstTime"] = "Tiempo Est.",
                ["TotalCost"] = "Costo Total",
                ["Template"] = "Plantilla",
                ["NoTemplate"] = "Sin plantilla",
                ["ProductionTemplate"] = "Plantilla de Producción",
                ["ProductionTemplateOptional"] = "Plantilla de Producción (Opcional)",
                ["SelectTemplateHelp"] = "Seleccione una plantilla para definir BOM y costos",
                // Shifts
                ["Shift"] = "Turno",
                ["Morning"] = "Mañana",
                ["Afternoon"] = "Tarde",
                ["Night"] = "Noche",
                // Common
                ["Notes"] = "Notas",
                ["ProductionNotes"] = "Notas de Producción",
                ["Cancel"] = "Cancelar",
                ["Save"] = "Guardar",
                ["Description"] = "Descripción",
                ["Optional"] = "Opcional",
                ["Required"] = "Requerido",
                ["FinishedGood"] = "Producto Terminado",
                ["FinishedGoodOptional"] = "Producto Terminado (Opcional)",
                ["ConfirmDelete"] = "Confirmar Eliminación",
                ["AreYouSure"] = "¿Está seguro de que desea eliminar esto?",
                ["TemplateName"] = "Nombre de Plantilla",
                ["ModelType"] = "Tipo de Modelo",
                ["EditPart"] = "Editar Parte",
                ["ParentPart"] = "Parte Padre",
                ["PartType"] = "Tipo de Parte",
                ["PartName"] = "Nombre de Parte",
                ["UnitCost"] = "Costo Unitario ($)",
                ["EstimatedMinutes"] = "Minutos Estimados",
                ["MaterialName"] = "Nombre del Material",
                ["MaterialCode"] = "Código del Material",
                ["MinimumStock"] = "Stock Mínimo",
                ["AddChildPart"] = "Agregar Parte Hija",
                ["ProductionOrder"] = "Orden de Producción",
                ["ExpectedDeliveryDate"] = "Fecha de Entrega Esperada",
                ["NewFinishedGoodEntry"] = "Nueva Entrada de Producto Terminado",
                ["RawMaterial"] = "Materia Prima",
                ["None"] = "Ninguno",
                ["RootLevel"] = "Nivel Raíz",
                ["Quantity"] = "Cantidad",
                ["ProductionDate"] = "Fecha de Producción",
                ["DailyProductionEntry"] = "Entrada de Producción Diaria",
                ["EnterProductionForDate"] = "Ingrese la Producción para la Fecha",
                ["EnterQuantitiesForEachProduct"] = "Ingrese las cantidades para cada producto",
                ["Units"] = "unidades",
                ["SaveDailyProduction"] = "Guardar Producción Diaria",
                ["NoActiveProductsFound"] = "No se encontraron productos activos. Por favor, agregue productos primero.",
                ["HistoricalDailyProduction"] = "Historial de Producción Diaria",
                ["NoProductionHistoryFound"] = "No se encontró historial de producción. ¡Comience ingresando su primera producción diaria!",
                ["ProductionOrdersManagement"] = "Gestión de Órdenes de Producción",
                ["MarkAsInProgress"] = "Marcar como En Progreso",
                ["MarkAsCompleted"] = "Marcar como Completado",
                ["EditProductionOrder"] = "Editar Orden de Producción",
                // MainLayout
                ["SwitchToLightMode"] = "Cambiar a Modo Claro",
                ["SwitchToDarkMode"] = "Cambiar a Modo Oscuro",
                ["Language"] = "Idioma",
                // Products page
                ["EditProduct"] = "Editar Producto",
                ["NoProductsFound"] = "No se encontraron productos. ¡Cree su primer producto!",
                ["CapacityLiters"] = "Capacidad (Litros)",
                ["NoTemplateSelected"] = "Sin Plantilla",
                ["TemplateCosts"] = "Costos de Plantilla",
                ["Total"] = "Total",
                ["ProductCreated"] = "¡Producto creado exitosamente!",
                ["ProductUpdated"] = "¡Producto actualizado exitosamente!",
                // Raw Materials page
                ["Category"] = "Categoría",
                ["MinStock"] = "Stock Mín.",
                ["NewMaterial"] = "Nueva Materia Prima",
                ["EditMaterial"] = "Editar Material",
                ["UnitFormat"] = "Unidad (kg, L, pzs)",
                ["LowStockAlertCount"] = "material(es) tienen stock bajo!",
                ["NoMaterialsFound"] = "No se encontraron materiales. ¡Cree su primer material!",
                ["Reason"] = "Razón",
                ["AddStock"] = "Agregar Stock",
                ["RemoveStock"] = "Retirar Stock",
                // Production Orders page
                ["CreateOrder"] = "Crear Orden",
                ["Start"] = "Iniciar",
                ["Complete"] = "Completar",
                ["NoOrdersFound"] = "No se encontraron órdenes de producción. ¡Cree su primera orden!",
                ["OrderAutoStarted"] = "Orden establecida automáticamente como En Progreso",
                ["OrderAutoCompleted"] = "Orden completada automáticamente - cantidad objetivo alcanzada",
                // Suppliers page
                ["EditSupplier"] = "Editar Proveedor",
                ["CompanyName"] = "Nombre de Empresa",
                ["ContactName"] = "Nombre de Contacto",
                ["NoSuppliersFound"] = "No se encontraron proveedores. ¡Cree su primer proveedor!",
                // Finished Goods page
                ["Order"] = "Orden",
                ["NoFinishedGoodsFound"] = "No se encontraron productos terminados. ¡Complete una orden de producción para crear productos terminados!",
                // Shippings page
                ["CancelShipmentAction"] = "Cancelar Envío",
                ["ShipmentUpdated"] = "Envío actualizado exitosamente",
                ["ShipmentCreated"] = "Envío creado exitosamente",
                ["ShipmentCancelled"] = "Envío cancelado exitosamente",
                ["ShipmentStatusUpdated"] = "Estado del envío actualizado",
                // Reports page
                ["ReportsAnalytics"] = "Reportes y Analíticas",
                ["ReportDesigner"] = "Diseñador de Reportes",
                ["ReportType"] = "Tipo de Reporte",
                ["ProductionSummaryReport"] = "Resumen de Producción",
                ["InventoryStatusReport"] = "Estado de Inventario",
                ["RawMaterialsUsage"] = "Uso de Materias Primas",
                ["OrdersAnalysis"] = "Análisis de Órdenes",
                ["CustomReport"] = "Reporte Personalizado",
                ["StartDate"] = "Fecha de Inicio",
                ["EndDate"] = "Fecha de Fin",
                ["Generate"] = "Generar",
                ["ReportOptions"] = "Opciones de Reporte",
                ["IncludeCharts"] = "Incluir Gráficos",
                ["IncludeDetails"] = "Incluir Detalles",
                ["GroupByProduct"] = "Agrupar por Producto",
                ["ExportPDF"] = "Exportar PDF",
                ["ExportExcel"] = "Exportar Excel",
                ["SaveTemplate"] = "Guardar Plantilla",
                ["ProductionSummaryReportTitle"] = "Reporte de Resumen de Producción",
                ["InventoryStatusReportTitle"] = "Reporte de Estado de Inventario",
                ["ProductTypes"] = "Tipos de Producto",
                ["AvgUnitsOrder"] = "Prom. Unidades/Orden",
                ["ProductionDetails"] = "Detalles de Producción",
                ["TotalMaterials"] = "Total de Materiales",
                ["LowStockAlerts"] = "Alertas de Stock Bajo",
                ["AttentionRequired"] = "Atención Requerida:",
                ["MaterialsNeedRestocking"] = "materiales necesitan reabastecimiento",
                ["Material"] = "Material",
                ["Shortage"] = "Faltante",
                ["CustomReportBuilder"] = "Constructor de Reportes Personalizados",
                ["CustomReportDescription"] = "Diseñe sus propios reportes seleccionando métricas, agrupaciones y visualizaciones específicas. Esta función le permite crear reportes adaptados a sus necesidades de negocio.",
                ["CurrentStatusAsOf"] = "Estado actual al",
                // Daily Production automation messages
                ["ProductionOrdersCreatedSuccess"] = "¡Órdenes de producción creadas exitosamente para {0} producto(s)!",
                ["EnterQuantityWarning"] = "Por favor, ingrese cantidades para al menos un producto.",
                ["ErrorCreatingOrders"] = "Error al crear órdenes de producción: {0}",
            }
        };
    }

    public async Task InitializeAsync()
    {
        try
        {
            var storedLanguage = await _jsRuntime.InvokeAsync<string?>("localStorage.getItem", "language");
            if (!string.IsNullOrEmpty(storedLanguage) && _translations.ContainsKey(storedLanguage))
            {
                _currentLanguage = storedLanguage;
            }
        }
        catch
        {
            // If localStorage is not available, use default language
            _currentLanguage = "en";
        }
    }

    public string Translate(string key)
    {
        if (_translations.ContainsKey(_currentLanguage) && _translations[_currentLanguage].ContainsKey(key))
        {
            return _translations[_currentLanguage][key];
        }
        return key; // Return key if translation not found
    }

    public async Task SetLanguageAsync(string language)
    {
        if (_translations.ContainsKey(language))
        {
            _currentLanguage = language;
            await _jsRuntime.InvokeVoidAsync("localStorage.setItem", "language", language);
            OnLanguageChanged?.Invoke();
        }
    }
}
